### ISSUE TITLE
Accessibility - Now Instructions Telling User to Tap "Done" to Save City

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Closure-App#12]
There are no instructions to tell the user to tap the "Done" link after they chose a city.

When a person has a long list cities that they scrolled to, they might assume tapping the cities saves it for them.

Also, it's weird having a "Done" button to go save a city and no back button to their list if they decide not to save any new cities.

**Comment by georgepliu** [comment]
This issue has been resolved and is reflected in the current build #11

**Comment by jfc3-dol** [comment]
Thanks, for adding "Done selecting cities" to the "Done" button.

I still think you might want to add an instruction for all users that you need to tap the "Done" button to save your selection. Some might think that by selecting a city would be enough. 

But I did notice you need to tap the "Done" button to get back to your list of cities.

I will close this issue and can reopen another one if we find people are having issues with this.
