### ISSUE TITLE
Need VoiceOver to Read Out States Name Instead of Initials

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Closure-App#14]
Need VoiceOver to read out the states name instead of initials. Such as "Davenport Iowa" instead of "Davenport I A".

By adding a description or "accessible label" to the state initials, it would help people understand what state the city they chose was in case there were two cities named the same in similar states.

An "accessible label" or description might not be the term I'm looking for in iOS development.

**Comment by georgepliu** [comment]
This issue has been resolved and is reflected in the current build #11

**Comment by jfc3-dol** [comment]
It's working as expected now, so I'm going to close the issue.
