### ISSUE TITLE
City Results Not in Alphabetic Order When Searching

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Closure-App#3]
Why when looking for a city the results are NOT in alphabetic order?

I was searching for "San Diego, CA". I typed in "san" and got a first result of "San Juan, PR", then "Mount Pleasant, PA", then a few other cities starting with "san". Next, I got "Meza, AZ", Phoenix, AZ", etc. before getting more cities that started with "san".

Can we alphabetize the results and remove the ones that don't match?

I understand "Mount Pleasant, PA", should be in the list because it has "san" in the name but most likely not what I'm looking for when typing "san". I'm looking for cities that start with "san" only.

See the two screenshots below.

Part 1

![city list starting with san not in alphabetic order - pat 1](https://user-images.githubusercontent.com/10423487/34783087-900e415c-f5f8-11e7-9a7a-f2aaa12da3f9.PNG)

Part 2

![city list starting with san not in alphabetic order - part 2](https://user-images.githubusercontent.com/10423487/34783085-8ffb515a-f5f8-11e7-9134-1efd27416296.PNG)

**Comment by georgepliu** [comment]
This issue has been resolved and is reflected in the current build #11

**Comment by jfc3-dol** [comment]
The search results are now in alphabetic order and don't seem to have additional cities listed.

There is a problem that I can not scroll the of cities found. Will create another issue so I can close this one because the sort problem has been corrected.
