### ISSUE TITLE
When Typing "ill" for "Illinois" in "State" Tab I Should See That State First

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Closure-App#8]
When I'm typing "ill" for "Illinois" in the "State" tab I should see that state first and not cities in other states. Plus. the cities are no even in alphabetic order anyway.

See screenshot below.

![closure - ill should show illonios cites in the state tab](https://user-images.githubusercontent.com/10423487/34849566-c8e310c2-f6f0-11e7-84c6-9febd13ddfb7.png)

**Comment by georgepliu** [comment]
This issue has been resolved and is reflected in the current build #11

**Comment by jfc3-dol** [comment]
The "By State" tab now only shows items for a given state such as "Illinois" when I search for "ill".

Again not able to scroll the entire list to see the items at the bottom of the list.

Going to close this issue and add a note to issue #15 that it applies to both the "By City" and "By State" tabs. Will check by region too.
