### ISSUE TITLE
Accessibility - Back Button is Read as "Button" and Not "Back Button"

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/Closure-App#9]
While using VoiceOver (screen reader) the back button is read as "button' not "back button" or "back to My Cities List" which would be better and more informative to the VoiceOver user.

See screenshot below.

![closure - the back button is read as button not back button](https://user-images.githubusercontent.com/10423487/34850557-52d6fdf4-f6f4-11e7-95e8-798acd610fd2.png)

**Comment by georgepliu** [comment]
This issue has been resolved and is reflected in the current build #11

**Comment by jfc3-dol** [comment]
Thanks, for adding the text "Navigating back to my cities" to the button so a screen reader (VoiceOver) user knows what the button is used for.

I'm closing this issues.
